
service: upc-iot-demo1 

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 30
  stage: dev

  environment:
    iotDataTableName: ${self:custom.iotDataTableName}
    iotGadgetTableName: ${self:custom.iotGadgetTableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ iotDataTable, Arn ]
        - "Fn::GetAtt": [ iotGadgetTable, Arn ]

package:
  exclude:
    - ./frontend/**

functions:
  postGadget:
    handler: src/handler.postGadget
    events:
      - http:
          path: api/gadget
          method: post
          cors: true
  getGadget:
    handler: src/handler.getGadget
    events:
      - http:
          path: api/gadget/{id}
          method: get
          cors: true
  getAllGadget:
    handler: src/handler.getAllGadget
    events:
      - http:
          path: api/gadget/
          method: get
          cors: true
  postData:
    handler: src/handler.postData
    events:
      - http:
          path: api/data/
          method: post
          cors: true
  getDataFromGadget:
    handler: src/handler.getDataFromGadget
    events:
      - http:
          path: api/data/{gadgetId}
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                fromMillis: true
                toMillis: true


resources:
  Resources:
    iotGadgetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.iotGadgetTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    iotDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.iotDataTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  stage: ${opt:stage, self:provider.stage}
  iotDataTableName:  ${self:service}-${self:custom.stage}-iotData
  iotGadgetTableName:  ${self:service}-${self:custom.stage}-iotGadget
